### PR TITLE
Only run unusedCompileDependenciesTest on the JVM

### PR DESCRIPTION
**Pull request by rossabaker**
Should help with https://github.com/http4s/http4s/pull/5926.

### CODE REVIEW

**Comment by armanbilge** [comment]
I'm not sure this will help us. The CI workflow is global to the whole build, not per-project.

What could help is if we added a conditional to this step that only runs if it is a JVM job. But this gets fiddly if we try and account for pure JVM (like the jdk client) or pure JS projects (like dom).

**Comment by armanbilge** [comment]
I know it doesn't help us right now, but what we should do is absorb the explicit deps plugin into sbt-typelevel and apply this fix:
- https://github.com/cb372/sbt-explicit-dependencies/pull/100

**Comment by armanbilge** [comment]
I have a fix incoming.

**Comment by rossabaker** [comment]
Oh, I thought this would run only on the JVM, but I did bake in an assumption everything was using cross project, which is probably not right.

**Comment by rossabaker** [comment]
#129 is better.

**Pull request closed without merging**
