### PR TITLE
Remove custom website template, add more logos

### PR DESCRIPTION
**Pull request by armanbilge**
Interestingly enough, if http4s decides not to hack the Laika template, then we can just use the one in sbt-typelevel. I'd say that's a win.

I've also upstreamed more logos.

Technically a breaking change, so we bump to 0.13.0.

### CODE REVIEW

**Comment by rossabaker** [comment]
I am so far underwater.  Can I get a refresher on how we've "hacked the template"?

**Comment by armanbilge** [comment]
To be fair, I don't claim to completely understand it myself. The main thing I'm trying to get rid of is this.

https://github.com/http4s/sbt-http4s-org/blob/05988b089e57d9f7f846b95cd4f475190d094f13/core/src/main/resources/org/http4s/sbt/site/default.template.html#L58-L63

I think it was part of the scheme to support pretty URLs that hugo was doing. But it seems to force every directory to contain a `README.md` which shows up in the navigation bar. I just want it to behave like the Laika site itself, which is very nicely organized into sections without any of this README stuff, and I can't do that right now.
https://github.com/planet42/Laika/tree/master/docs/src

**Comment by rossabaker** [comment]
I vaguely recall Jens doing some acrobatics to keep the URLs as they were, and then you mentioned we might have to punt on that.  I think these two are related.

**Comment by armanbilge** [comment]
Yep. Admittedly I'm running low on patience, but I just want to get things down to a minimal config setup. I'm also trying to merge the two site projects into one because it's caused all sorts of headaches.

After all this, we'll see what we can do about the URLs.

**Comment by armanbilge** [comment]
I'm going to merge this because I want the snapshot, but let's not release until we arrive at something we're happy (enough) with.

**Comment by armanbilge** [comment]
Yeah, I mean look at this. On the current live site the same page shows up twice, and one of those is `README.md` in the menu. I don't know what's wrong and I don't care. No more hacks.

https://http4s.org/v1.0/index.html
https://http4s.org/v1.0/index/index.html

**Pull request merged**
