### PR TITLE
 Bump some dependencies

### PR DESCRIPTION
**Pull request by rossabaker**
Not sure why Scala Steward isn't seeing the plugins.

### CODE REVIEW

**Comment by fthomas** [comment]
> Not sure why Scala Steward isn't seeing the plugins.

I guess they don't show up in the `libraryDependencies` of the build or the `plugins` project. What happens if `addSbtPlugin` is used inside `.settings()`? To which setting or tasks are they added?

**Comment by rossabaker** [comment]
`addSbtPlugin` is currently used in core's `settings` to declare plugins that the core project depends on.  I'm not sure that it's the correct idiom.

**Comment by fthomas** [comment]
I checked the `libraryDependencies` and it indeed contains the plugins that are updated in this PR. It turned out that an "optimization" in Scala Steward prevents it from updating them. The good news is that this optimization is probably not needed any more and can be removed. I'll check that.

**Comment by rossabaker** [comment]
The floodgates have opened. Thanks for finding this!

**Comment by rossabaker** [comment]
Merging this to pick up the Scala bump.

**Pull request merged**
