### PR TITLE
sbt-spiewak-sonatype-0.21.0

### PR DESCRIPTION
**Pull request by rossabaker**
Should be enough for Scala 2.13.6 support.

### CODE REVIEW

**Comment by aeons** [comment]
Bah, off by 7 minutes :D

**Comment by rossabaker** [comment]
If we release this, we'll be back on Java 16, and might see that flaky test in the main repo again, but I guess it's time to fix it.  We test on Java 16 for a reason.

**Comment by aeons** [comment]
The one with gzip or something else?

**Comment by rossabaker** [comment]
Yes, that sounds right.  We'll probably find out as soon as we bump to this. :smile:

**Comment by aeons** [comment]
I disabled that when jvm version == 16

**Pull request merged**
