### PR TITLE
Support Dotty

### PR DESCRIPTION
**Pull request by rossabaker**
* Turns off backend parallelism in Dotty
* Disables silencer plugin and dependency in Dotty

### CODE REVIEW

**Comment by rossabaker** [comment]
@Daenyth: in your `@nowarn` tricks, are you able to drop any of these dependencies?

**Review by aeons — APPROVED** [review]

**Comment by Daenyth** [comment]
I haven't tried, I just depend on them - they're in my classpath anyway, and both libraries have a history of very solid compat

**Comment by rossabaker** [comment]
@Daenyth Oh, sorry, I meant the silencer runtime libraries.

**Comment by Daenyth** [comment]
I think it's just `% Provided` scope so it doesn't actually get included in any way

**Comment by rossabaker** [comment]
Yeah, we have it in `CompileTime` and in `Test`, so we have to drag it around our build, but it doesn't impact downstream.  I think that's good enough.

**Pull request merged**
