### PR TITLE
Add sbt-api-mappings plugin

### PR DESCRIPTION
**Pull request by rossabaker**
See https://github.com/http4s/http4s-jetty/pull/10.  Nobody should have to think about this stuff.

### CODE REVIEW

**Comment by armanbilge** [comment]
Tbh I don't really understand what sbt-api-mappings does. It says it only configures stuff for common Scala libraries, so I don't see how it helps with Jetty. Meanwhile, fixing API mappings is IMHO an upstream problem, and it's unclear to me how this plugin interact with sbt's built-in mechanism for this. E.g. see:
- https://github.com/playframework/play-json/pull/756

**Comment by rossabaker** [comment]
Pretty sure [this rule](https://github.com/ThoughtWorksInc/sbt-api-mappings/blob/872829939dbf80931b3f670b274fe8f7e394d481/src/main/scala/com/thoughtworks/sbtApiMappings/JavadocIoApiMappingRule.scala) fixes Jetty.  It takes advantage of all Central dependencies being on javadoc.io.

I don't think "upstream mappings" are a concept outside SBT.  Does anything else set that apiURL property in the POM?

I don't know whether this introduces false positives.  Probably, if SBT doesn't resolve the external sources?  But I got frustrated after I patched Jetty when it then couldn't find the JDK.

**Comment by armanbilge** [comment]
Yeah I should spend more than a minute trying to understand it before gabbing off. Currently the combination of `apiURL` with the `TypelevelUnidocPlugin` is working really nice and I' wouldn't want this to override that :)

**Comment by rossabaker** [comment]
* `apiURL` is a publisher setting, that adds metadata to the POM.  It isn't a standard I can find anywhere.
* `autoAPIMappings` is a consumer setting, that respects the metadata created by `apiURL`.  In an ecosystem that uses the same build tool and the same plugins, this works pretty well!
* `apiMappings` is a way to fix it for libraries that don't participate in this system.  That will be most (all?) of Java.
* `apiMappingRules` is a custom thing introduced by this sbt-api-mappings plugin to generate `apiMappings`.
* I'm surprised that the JDK doesn't work out of the box with vanilla SBT!

I guess we can fix the JDK in sbt-typelevel, manually fix jars in projects if we're scared about false positives on javadoc.io, and call it a day.  But I don't think any of this will disturb unidoc functionality.

**Comment by armanbilge** [comment]
Right, I'm specifically staring at the `apiMappings` setting which is a `Map`. IIUC sbt populates it when `autoAPIMappings` is enabled and so does the sbt-api-mappings plugin.

https://github.com/ThoughtWorksInc/sbt-api-mappings/blob/872829939dbf80931b3f670b274fe8f7e394d481/src/main/scala/com/thoughtworks/sbtApiMappings/ApiMappings.scala#L48

So my question is, who gets the final say on what goes in there?

After experimenting with it, empirically it does seem to be doing the right thing. So it's probably fine. Ideally I'd like to understand why though.

**Comment by rossabaker** [comment]
If I leave `autoAPIMappings` alone and set `doc / apiMappings`, it works on 2.12 but not 2.13.  If I instead set `apiMappings` , it works on 2.13 but not 2.12.

**Comment by armanbilge** [comment]
Yeah, idk, it's these weird interactions that make it hard to know for sure what will or won't change/break. Anyway I opened an upstream PR that ensures sbt-api-mappings settings are used only as a fallback, which I think alleviates my concerns.
- https://github.com/ThoughtWorksInc/sbt-api-mappings/pull/117

**Comment by rossabaker** [comment]
The 2.12 vs. 2.13 weirdness is that the javadoc linking is baked into 2.13, but not 2.12.  I got it working on http4s-jetty with a pair of simple `apiMappings`.  If we add the Java one here (or sbt-typelevel), we can conservatively do the Jetty jar in the Jetty project, and not add another plugin dependency.

**Comment by armanbilge** [comment]
Sure, seems good to upstream it into sbt-typelevel. What's the magic incantation you came up with? :)

**Comment by rossabaker** [comment]
https://github.com/http4s/http4s-jetty/pull/10/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R76-R99

I'm not sure where to put it in sbt-typelevel.  I don't think it has anything to do with Sonatype.

**Comment by armanbilge** [comment]
Thanks. I don't really know either, I guess it can go in the Typelevel settings plugin.

**Pull request closed without merging**
